name: Swift

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.5.2"
        xcode-version: latest
    - name: install tuist
      run: curl -Ls https://install.tuist.io | bash
    - name: install Cocoapods
      run: sudo gem install cocoapods
    - name: project Generate
      run: |
        rm -rf Podfile.lock
        tuist generate
        pod install
    - name: Tests
      run: |
        xcodebuild clean test -workspace MOIZA.xcworkspace -scheme 'MOIZATest' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
        xcodebuild clean test -workspace MOIZA.xcworkspace -scheme 'MOIZAUITest' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
